### ISSUE TITLE
Здравствуйте

### ISSUE THREAD

**Issue by emresha** [Nna2291/chessClient#1]
дочь скачяла ваше приложение, захожу, а там просит ДАННЫ Е КДРТИНОЙ КАРТОЧКИ!!!!1!!!
моя дочь ввела и у меня сняли все денги!! (346 тенге)
опжалуйста разрабочики верните деньи.

**Comment by Nna2291** [comment]
Здравствуйте, напишите пожалуйста на почту: notscam100percent@gmail.com
